<option value="1">Adrar</option>
<option value="2">Chlef</option>
<option value="3">Laghouat</option>
<option value="4">Oum bouaghi</option>
<option value="5">Batna</option>
<option value="6">Bejaia</option>
<option value="7">Biskra</option>
<option value="8">Bechar</option>
<option value="9">Blida</option>
<option value="10">Bouira</option>
<option value="11">Tamanrasset</option>
<option value="12">Tebessa</option>
<option value="13">Tlemcen</option>
<option value="14">Tiaret</option>
<option value="15">Tizi ouzou</option>
<option value="16">Alger</option>
<option value="17">Djelfa</option>
<option value="18">Jijel</option>
<option value="19">Setif</option>
<option value="20">Saida</option>
<option value="21">Skikda</option>
<option value="22">Sidi Bel Abbes</option>
<option value="23">Annaba</option>
<option value="24">Guelma</option>
<option value="25">Constantine</option>
<option value="26">Medea</option>
<option value="27">Mostaganem</option>
<option value="28">M'sila</option>
<option value="29">Mascara</option>
<option value="30">Ouargla</option>
<option value="31">Oran</option>
<option value="32">El Baydh</option>
<option value="33">Illizi</option>
<option value="34">Bordj Bou Arreridj</option>
<option value="35">Boumerdes</option>
<option value="36">El Taref</option>
<option value="37">Tindouf</option>
<option value="38">Tissemsilt</option>
<option value="39">El Oued</option>
<option value="40">Khenchla</option>
<option value="41">Souk Ahrass</option>
<option value="42">Tipaza</option>
<option value="43">Mila</option>
<option value="44">Aïn Defla</option>
<option value="45">Nâama</option>
<option value="46">Aïn Temouchent</option>
<option value="47">Ghardaïa</option>
<option value="48">Relizane</option>

